### ISSUE TITLE
Run without electron

### ISSUE THREAD

**Issue by linonetwo** [reZach/secure-electron-template#11]
It is said that

```
target: 'web', // Our app can run without electron
```

in webpack.config.js

But when I tried `npm run dev-slim`, it gives :

```
TypeError: window.api is undefined
```

---

This seems unavoidable since you are to `import i18n from '../localization/i18n.config';` which needs `window.api` to communicate with the backend.

**Comment by reZach** [comment]
@linonetwo This comment was written before I got localization working, the intent was that running without electron can be a quicker development process and to conceptually prove the architecture (to me) that to run a secure electron app, you have a web project you run on it's own, and then wrap with electron.

Since this _is_ an electron template, I'm considering now to drop the `dev-slim` command. Do you have any use case for using `dev-slim`?

**Comment by linonetwo** [comment]
No, I ask just out of curiosity~

I'm creating a game using your template.

Thank you for your great work!

**Comment by reZach** [comment]
@linonetwo gotcha! What game are you creating? I am curious if you'd like to share.

**Comment by linonetwo** [comment]
I'm just practicing, using react-pixi-fiber for rendering and react-entity-component-system for state management.

I haven't made a game before, but I found it is pretty easy to create a game using react and electron.

<img width="1260" alt="Screen Shot 2020-02-07 at 2 19 56 PM" src="https://user-images.githubusercontent.com/3746270/74006019-70499480-49b5-11ea-8c06-0e4e5e83634d.png">

Its code is at

https://github.com/linonetwo/electron-react-game-dev-playground/tree/demo

I load pictures assets using handlers in preload script, so I can load pictures assets from fs, so I can support mod system.
