### ISSUE TITLE
doesnt work out of the box

### ISSUE THREAD

**Issue by nphias** [reZach/secure-electron-template#13]
various errors. .babelrc missing,  wrong case on all paths

for such merticulous documentation .. one would have thought you would have the basics working
 but anyway thanks for sharing...

**Comment by reZach** [comment]
Hi @nphias,

Thanks for trying out the template, can you tell me more what you mean with what you are finding. The `.babelrc` is in the root of the project, and I do not know what you mean by "wrong case on all paths." 

I'd be happy to enhance the project if I know what is wrong with it and I have the capacity to do so. Hope to hear back from you.

**Comment by nphias** [comment]
right sorry that was my mistake about .babelrc.
in order to run your demo.. i had to correct half of all the paths to jsx files
running with npm run dev .. gives a blank screen
running with npm run prod..  menu doesnt appear...  and i cant debug as console is somehow blocked

**Comment by reZach** [comment]
@nphias if there are pieces of instruction that would help you use this template, please let me know what you had trouble with so I can add additional details in here. I too when working with Electron/react for the first time I had trouble with a bunch of pieces understanding how they worked or what they did.

I also wanted to post a few notes:
- The white screen comes up because the webpack dev server is bundling the files after running `npm run dev`.
- The dev tools are disabled in production because it's an attack vector that we will want closed. This is configured in [main.js](https://github.com/reZach/secure-electron-template/blob/master/app/electron/main.js), where we configure the BrowserWindow that is the main Electron application.
