### ISSUE TITLE
boilerplate without any framework

### ISSUE THREAD

**Issue by Sparkenstein** [reZach/secure-electron-template#15]
Great work on integrating all the must have security things in one place.
This is something every electron app should have. Unfortunately I don't really use react everywhere, especially with Redux. I wanted to create vanillajs electron apps. 

Can we have a standard boilerplate without hard dependency on any framework? So that people who want to work with Vue or Angular will be able to just integrate themselves. And people who want to use it without framework are free to do so.

If creating another repo is harder, maybe we can just mention the steps to remove framework from existing app.

**Comment by reZach** [comment]
Thanks @Sparkenstein.

If you are looking for a vanilla template, I think it's the best course of action to create a new repository, likely a fork of this one that could initially be set up to remove all the dependencies and then it's pure vanilla.

I was debating "what if we put it in here?" but then it makes it complicated because then I'd have to update the template in two locations and I only really intended to use this with react/redux (of course that's why it's MIT licensed - so if people desire no frameworks then they can work towards that 😄).

Are you comfortable enough with that suggestion? I can give you places where you'll have to rework the template to remove the frameworks. You'll be removing localization and undo/redo support, but I assume you didn't care about that (ie. a "vanilla" template is more important).

**Comment by Sparkenstein** [comment]
Thanks for the reply @reZach 
I actually started working on a template in my free time. So far I have removed Redux only :stuck_out_tongue:  But I plan to create one repo without any framework as well.
I agree than two different repos doing the same work differently, shouldn't be at the same place, I will surely push the work I have done as soon as it's finished.

Thanks for helping :D

**Comment by reZach** [comment]
@Sparkenstein there [are steps](https://github.com/reZach/secure-electron-template/issues/57#issuecomment-777891491) which you may follow to make this a JS-only template. They are _proposed_ changes and may not reflect all the work that is necessary for this template.

**Comment by Sparkenstein** [comment]
That is excellent. I am so sorry I created my own version at that time but forgot to update on this issue. my version is outdated now, but can be updated with simple commands:

https://github.com/fosslife/secure-electron-react

just an FYI this template _just_ removes redux and some extra stuff, and does not change any recommended security guidelines
