### ISSUE TITLE
Antivirus software caught package here as a "Trojan"

### ISSUE THREAD

**Issue by mishkinf** [reZach/secure-electron-template#22]
Upon installing the node modules my virus protection Bitdefender caught a file installed during npm i as a trojan. Seems a bit disconcerning for a project revolving around security of apps..
Any idea whats going on here?

<img width="721" alt="Screen Shot 2020-05-22 at 11 53 24 AM" src="https://user-images.githubusercontent.com/707663/82700472-1cd91a80-9c23-11ea-8a6a-c7310d92306c.png">

**Comment by reZach** [comment]
Hi @mishkinf , thanks for reporting this issue. I admit it took a little bit to figure out, but it looks like a false-positive due to a bug in [app-builder](https://github.com/develar/app-builder/issues/33). I've [reported a bug](https://github.com/electron-userland/electron-builder/issues/5004) to get this resolved and also downgraded electron-builder to a version prior (currently 21.2.0) where the .exe.zip file was not included.

If you get the latest release, v4.0.6, you should not have problems with this file with your antivirus software.

Let me know if this answers all the questions you may have - and thanks for using the template!

**Comment by mishkinf** [comment]
thanks for the quick investigation @reZach ! Props to the good work.

**Comment by reZach** [comment]
@mishkinf I've pushed a [fix](https://github.com/reZach/secure-electron-template/releases/tag/v4.0.8) for this, I'm not seeing the .exe.zip in the node_modules folder after the dependency was updated. Please re-open this after pulling the latest if you still have an issue 😄 .
