### ISSUE TITLE
Question: shouldn't this repo be GPL (2)?

### ISSUE THREAD

**Issue by mmercdispose** [reZach/secure-electron-template#39]
Hi,
since you are using https://github.com/reZach/secure-electron-template/blob/master/app/electron/protocol.js which has GPL(2) inside, I think this implies that the whole solution should be GPL(2).

I have read a few articles about it(no expert in law) but this is the conclusion I got, according to https://www.quora.com/What-are-the-key-differences-between-the-GNU-General-Public-license-and-the-MIT-License this is repo is actually the "derivative work" that means you can not put MIT but only GPL(2). https://www.google.com/search?q=gpl+derivative+work&source=lmns&bih=766&biw=1440&rlz=1C5GCEM_enUS918US918&hl=en&sa=X&ved=2ahUKEwjyzLjGpv_sAhXNhqQKHbRdBCQQ_AUoAHoECAEQAA

**Comment by reZach** [comment]
Great point @mmercdispose!

Since I spoke with @moloch-- and used some of his code to fix [this bug](https://github.com/reZach/secure-electron-template/issues/2), I'm going to ask his permission if he can license this particular code as MIT. Otherwise, and I am no lawyer, I think you are right this repository should be licensed under GPL.

**Comment by moloch--** [comment]
That particular code is from https://github.com/moloch--/reasonably-secure-electron (GPLv2)

**Comment by reZach** [comment]
@mmercdispose Closing as the repo is now switched over to GPL v2 [commit](https://github.com/reZach/secure-electron-template/commit/cdb3c49f36abe6f67d9f4fc0cad681c5145c7c97). Thanks for pointing this out.
