### ISSUE TITLE
[Question] Appropriate way to load non-packaged files from the local Filesystem?

### ISSUE THREAD

**Issue by ChristianTucker** [reZach/secure-electron-template#46]
Hey there, I'm getting started with electron and happened to come across your repository and have read most of the documentation on your packaged modules. 

I'm having some trouble with rendering images from a selected directory in the FileSystem.  Currently, I'm using the menu to create a dialog that lets me choose a directory. I'm then using IPC to send the information related to those files to the renderer thread. This information currently consists of...

- Absolute Directory
- File name
- File size
- File type 

However, when attempting to load the image through a `file://` URL I get the following error: `Not allowed to load local resource:`

I then decided I could try to load all of the image data and send the `Buffer` over IPC to be stored in my Redux Reducer, however as you can imagine this is quite slow compared to on-demand reading. However, these buffers can't be rendered without encoding them in base64 so it causes even more performance loss. 

**Just wondering what you would recommend for this? I'm basically making a miniature file explorer (albeit inside of a project directory) that serves as the asset selection component of my game's map editor.** 

The best-idea I've had with the workarounds I've found is to use something like imagemagick on the main thread to resize and encode the images and keep thumbnails in base64 format in the reducer, this isn't optimal, but it's the only solution I've come up with for the time being. 

This however, is a problem when it comes to rendering the world inside of PixiJS as I need the image at full scale. I guess around this point I could use IPC again to request the full image in Base64 format and then render it. But I feel like this makes the app feel a lot less responsive. 

**EDIT:** I wasn't really sure where to ask this, but since most recommendations include disabling security features, I assumed this was the best place.

**Comment by reZach** [comment]
Thanks for opening this up @ChristianTucker.

Looks like the loading of local resources is blocked by Chrome (for obvious security reasons). The [switches](https://www.electronjs.org/docs/api/command-line-switches) don't include the [switch](https://stackoverflow.com/a/53320849) (see link in answer) that would allow this to be bypassed in electron.

_Honestly_ I think you will have to pass the base64 encoded data to your renderer process in order for the app to stay secure, unless you'd like to remove security recommendations you've found. (Sometimes security can make performance a bit slower). If you do end up using the IPC route, I'd recommend only pulling the thumbnails for images you need to render in your application, then requesting the full-size ones on demand (to reduce potential of less-responsiveness in your app). 

Another option, which may or may not pan out, would be to make some modifications (or a separate package, perhaps??) like I did [here](https://github.com/reZach/secure-electron-store#using-the-unprotected-store-new-since-v130). The idea would be to preload all the image data in a given directory/subdirectories when the app starts up so that you wouldn't have to request images while using the app. I don't know if this fits your use case but it's something to think about/consider.

**Comment by ChristianTucker** [comment]
Thanks for the response @reZach.

Currently I'm going the route of creating thumbnails for the art and storing the base64 data in a redux reducer as I explained before, I'm also having to do some hacky workarounds to get my content to render within my Pixi application as it also cannot access the local filesystem. The result however is what I would expect. (From filesystem -> DOM -> Canvas)  

[Example](https://gyazo.com/9d80975acbfb94338d0f9e27a4f834ba.gif)

------

Do you happen to know if there's a maximum size that can be communicated over IPC?  Later on, as this project evolves and gets closer to a proper release I can see situations where people are loading directories with potentially thousands of images. There's also images at a large scale that could be loaded, for example 4k and 8k images which could easily start bringing base64 data into possibly >100MB of data. This may already potentially be a problem for the electron renderer, but I like to consider all use-cases when developing. 

Currently the way I'm doing things is very similar to the use-case you provided, however, I'm loading everything [thumbnails only] once the project directory is selected by the end-user. There's also the fear of a maximum size of data allowed in a redux-store.

**Comment by reZach** [comment]
You're welcome @ChristianTucker.

It looks like [_this_](https://chromium.googlesource.com/chromium/src/+/master/ipc/ipc_channel.h#144) might be the maximum size? (Not sure what the value of that number is in though). So you may need to (if you encounter it), chop the image into multiple messages to send over to the renderer process if you ever get to that point.

As for the redux store max limit, you may also need to possibly consider 4/8k only stores for large images, or otherwise save the images in chunks, or perhaps forego the store and save it outside the store (ie. in a react component once sent over IPC).

**Comment by ChristianTucker** [comment]
No problem, @reZach your input has been more than helpful. Thanks for creating this repository, there was a lot of conflicting information out there and while I don't fully understand the security risks of an electron application, I want to make sure I'm doing everything within my power to do things correctly for any potential consumers.
