### ISSUE TITLE
[Question] How to use TypeScript with this template

### ISSUE THREAD

**Issue by denexapp** [reZach/secure-electron-template#47]
Hi, I'm relatively new to Electron and I've never used electron-builder. 

So I'm not sure is it a question for FAQ or a feature request, but it would be cool to know how to use TypeScript with this template.

**Comment by NiloDrumond** [comment]
> Hi, I'm relatively new to Electron and I've never used electron-builder.
> 
> So I'm not sure is it a question for FAQ or a feature request, but it would be cool to know how to use TypeScript with this template.

Hi,

It's actually not very hard to setup typescript for this template.

I just followed this guide and I don't remeber having any errors: https://medium.com/swlh/2020-settings-of-react-typescript-project-with-webpack-and-babel-403c92feaa06

**Comment by reZach** [comment]
Assuming @NiloDrumond's link suffices, closing this issue unless more discussion is needed.

**Comment by netpoetica** [comment]
I would argue that there is no way to follow that guide *without* not getting any errors :)

The problem to me seems to be twofold here. Firstly, the weboack.config.js and associated development and production overrides are specifically for app/src JavaScript. It is trivial to add TypeScript support such that you can compile src/ JS. That is no problem.

The real question though is, how do you take the code in app/electron and convert those into TypeScript files? Files such as preload.js, main.js, protocol.js and menu.js - these files are being loaded by electron shell, as far as I can tell, by way of the package.json "main" entry point, and pointing those to a .ts file will cause trouble, because the electron shell does not know to pump ts through webpack/babel/tsc and load a main.js (with sourcemaps) rather than main.ts (which will throw errors, as it is not a JavaScript file).

I attempted to make a separate webpack config that takes app/electron/*.ts and converts it to build/main.js, and then point package.json's "main" to build/main.js, but from this arises a whole slew of issues. I am not 100% clear on what these issues are.

TypeScript Forge uses a .js in their package.json "main", so I think I am in the right direction here: https://github.com/electron-userland/electron-forge/blob/master/packages/template/typescript-webpack/package.json#L8

But electorn forge does some quirky magic nonsense here that I don't think this template wants to have to contend with: https://github.com/electron-userland/electron-forge/blob/master/packages/template/typescript-webpack/tmpl/index.ts#L5

Anyhow I am poking at it, I will try to get an answer but I am not confident I have any proper sense of how to get the electron main (app/electron/*) to support being .ts files for this template at the moment

**Comment by netpoetica** [comment]
FWIW easiest win here would probably be something like

1. change package.json main to point to something like build/electron
2. make package.json script to `tsc` app/electron/*  into build/electrn
3. add step to run package.json tsc script before launching electron

I am trying this strategy and will keep posted for future viewers of this ticket

**Comment by netpoetica** [comment]
Here is what I did:

```
// package.json
-  "main": "app/electron/main.js",
+  "main": "build/electron/main.js",
   "scripts": {
+    "compile:electron": "tsc -p tsconfig.json",
```
add tsconfig.json
```
{
  "include": [
    "app/"
  ],
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "allowJs": true,                       /* Allow javascript files to be compiled. */
    "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    "sourceMap": true,                     /* Generates corresponding '.map' file. */
    "outDir": "./build/",                     /* Redirect output structure to the directory. */
    "strict": true,                           /* Enable all strict type-checking options. */
    // NOTE: Need to do this until we fix up those electron JS files.
    "noImplicitAny": false,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```
then, rename electron/*.js to electron/*.ts

and then you're gonna have to fix up a couple of issues that arise during complication in `npm run compile:electron`.

Now when you run `npm run compile:electron && npm run dev`, you should be good. Hope this helps someone in the future! I think there is a much, much better way to do this most likely that involves somehow injecting into the webpack/babel process being used by electron (if there is any), but I don't know.

**Comment by NiloDrumond** [comment]
@netpoetica  I have another solution, that can't evaluate if it is objectively better, but it doesn't require compiling manually before running. I simply use `@babel/preset-typescript`   and set webpack.config to `entry: ["./app/src/index.tsx"]` . You can check my version here: https://github.com/NiloDrumond/secure-electron-template-typescript

I have been planning to make a version of this template with typescript (and probably with eslint/prettier too) but never had the time. I might do it now.

**Comment by tyler-hitzeman** [comment]
For those just interested in the trivial implementation of TypeScript (transpiling stuff in `app/src`, but not `app/electron`), I made a demo here: https://github.com/tyler-hitzeman/secure-electron-template-ts/pull/1

**Comment by reZach** [comment]
I've made the changes suggested by @tyler-hitzeman (thank you Tyler) in his PR to the template [in a new release](https://github.com/reZach/secure-electron-template/releases/tag/v18.0.0). Typescript isn't supported in the app/electron folder, but that can be approached later.

**Comment by Dzuelu** [comment]
Upgrading my own template to TS, and it's quite an ordeal. Not sure you want it pushed upstream tho considering some people want a pure JS version too. The `secure` packages bundled also need some d.ts files to work easier, I made the following PRs if you could look over them @reZach.
https://github.com/reZach/secure-electron-store/pull/15
https://github.com/reZach/i18next-electron-fs-backend/pull/26
https://github.com/reZach/secure-electron-context-menu/pull/10
https://github.com/reZach/secure-electron-license-keys/pull/3
