### ISSUE TITLE
[Question] How do I access the data from main process in renderer process?

### ISSUE THREAD

**Issue by ransome1** [reZach/secure-electron-template#50]
Hi there.

I have a beginners question. I managed to follow you example and am receiving data from the main process in my renderer process. But I can only access it within the window.api.receive function and I just can't figure out how to make it accessible to the rest of the renderer functions.
![image](https://user-images.githubusercontent.com/11188741/106354144-d8446980-62ef-11eb-9c9b-c303f0a09906.png)

Can you give me a quick hint on how to make the data available outside the receive function?

Thanks a lot!

**Comment by reZach** [comment]
Hi @ransome1. 

Variables in JS are defined within the _scope_ that they are declared in. Defining a variable using `var` defines the variable within a functional scope. This means that `config` is only going to be defined within the function it was declared in, ie. 
```js
(data) => {
    var config = data;
}
```

Because you are trying to reference that same variable _outside_ the function, it will not be defined.

> Note, using `let` or `const` defines variable within the block-scope, or within a set of curly brackets. This behavior is more similar to defining variables in a language like C#, for example.

Here's two examples of what you can do to persist the value outside the `.receive` call. Either should work. I'd opt for example 1 if this value needs to be manipulated after the initial retrieval from the main process. Hopefully this gets you where you need to go with the template.

## Example 1
```jsx
import React from "react";

class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      config: {}
    };
  }

  componentDidMount() {
    // store a reference to the component itself
    const _ = this;

    window.api.receive("fromMain", (data) => {
        // save the config object into the react component's state
        _.setState({
            config: data
        });    
    });
  }

  render() {
    return (
      <div>
        My component
      </div>
    );
  }
}

export default MyComponent;
```

## Example 2
```jsx
import React from "react";

class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {}; // not used here
    this.config = {};
  }

  componentDidMount() {
    // store a reference to the component itself
    const _ = this;

    window.api.receive("fromMain", (data) => {
        // save the config object into the private variable of the component
        _.config = data;
    });
  }

  render() {
    return (
      <div>
        My component
      </div>
    );
  }
}

export default MyComponent;
```

**Comment by ransome1** [comment]
@reZach Thanks for the code. Do you by accident have a vanilla js example too? I don't use react.

**Comment by reZach** [comment]
> 
> 
> @reZach Thanks for the code. Do you by accident have a vanilla js example too? I don't use react.

I imagine this is a better example for you?

```html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8"/>
    <title>Title</title>
</head>
<body>
    <script>
        var mydata;
        window.api.receive("fromMain", (data) => {
            console.log(`Received ${data} from main process`);
            mydata = data;
        });
        window.api.send("toMain", "some data");

        // use data now
        console.log(mydata);
    </script>
</body>
</html>

```

**Comment by ransome1** [comment]
The example is great, but leads to the same result than in my first approach.

![image](https://user-images.githubusercontent.com/11188741/106368530-69e0c500-634a-11eb-8b03-0d817d0112dd.png)

**Comment by reZach** [comment]
> 
> 
> The example is great, but leads to the same result than in my first approach.
> 
> ![image](https://user-images.githubusercontent.com/11188741/106368530-69e0c500-634a-11eb-8b03-0d817d0112dd.png)

`config` will be populated _after_ the code in `.receive` has been called, but once it's populated you'll be able to use `config` elsewhere, does this make sense? 

Your first approach won't work because the function in `receive` is not called before you log `config`. If you change the code to this, you will see what I mean.

```js
var config;
window.api.receive("fromMain", (data) => {
  config = data;
  console.log("received response from main");
});
window.api.send("toMain", "getConfig");
console.log("logging value: " + config);
```

**Comment by reZach** [comment]
You can also try a callback approach but you'll see the obvious work that's involved.

```js
var config;
var callback = function(){
    // will be populated
    console.log(config);
};
window.api.receive("fromMain", (data) => {
  config = data;
  callback();
});
window.api.send("toMain", "getConfig");
```

**Comment by ransome1** [comment]
Thanks for you effort helping me here. The first example has the same outcome then before, the config later on is undefined. I guess I just understand how 

In the second example the config will be populated within the callback function. But how do I make the config available to other functions?

My goal is the access the config right after it has been populated, like so
```
var config;
var callback = function(){
    // will be populated
    console.log(config);
};
window.api.receive("fromMain", (data) => {
  config = data;
  callback();
});
window.api.send("toMain", "getConfig");

language = config.language;
```

There will a lot more code parsed right after that and the config object needs to available outside the callback function.

**Comment by reZach** [comment]
You are welcome @ransome1.

Here are some options, I'd suggest reading [this](https://www.freecodecamp.org/news/how-to-deal-with-nested-callbacks-and-avoid-callback-hell-1bc8dc4a2012/) since it is written well. 
I personally tend to rely on React/state which allows me to avoid the suggestions in this article. Since you are intending to work in just JS, the solutions in this article should lead you down the right path.

**Comment by ransome1** [comment]
Thanks a lot @reZach, much appreciated!
