### ISSUE TITLE
how to include web pages in a secure way?

### ISSUE THREAD

**Issue by kipop** [reZach/secure-electron-template#73]
hey, i am relatively new to javascript, can someone please explain how to include web pages in my electron app?
they seem to get blocked and i dont know how to enable them securely. (i tried using an <iframe> and a < webview >).
(if this is the wrong way to ask this sort of question let me know where i should post it instead
)

**Comment by kipop** [comment]
if this is the wrong way to ask this sort of question let me know where i should post it

**Comment by Slapbox** [comment]
@kipop if you're new to JavaScript I'd really advise that you not start with Electron, or at least accept that your work is not going to be very secure. Even when you're pretty well versed in what you're doing, Electron opens a larger attack surface than a webpage and it allows for attacks to be escalated much further because the code potentially has the privileges of a full application, not just a sandboxed webpage.

Your best bet if you need to use Electron is to use the `sandbox` option when you create your `BrowserWindow`. This will greatly limit what you can do with Electron, but it will certainly make it more secure.

I'd strongly recommend that you play around using Electron Fiddle at first as that will let you iterate and learn _much_ faster. Once you have your bearings, then start studying this repo more and more for better security practices as you begin to build your real app.

But again, in summation, Electron is harder to make secure and riskier to leave insecure - so be wary.

**Comment by Slapbox** [comment]
By the way, I'm guessing these lines are what's keeping you from loading the webpages you're trying to load:

https://github.com/reZach/secure-electron-template/blob/892aee037ca8f1d1581c5b314508737333340bb0/app/electron/main.js#L212-L226

**Comment by reZach** [comment]
@kipop I'm assuming you figured this out? I will close out this issue if I don't hear of a response in a week.
