### ISSUE TITLE
"win" Object passed to "i18next-electron-fs-backend" has been destroyed

### ISSUE THREAD

**Issue by linonetwo** [reZach/secure-electron-template#9]
Even I change the "close" event handler to:

```js
  win.on('closed', event => {
    event.preventDefault();
  });
```

The `win` object still got destroyed, because I can change "activate" handler to this:

```js
app.on('activate', () => {
  if (win.isDestroyed()) {
    createWindow();
  }
});
```

And it will recreate the window. This means, though `win` is not `null`, it is actually destroyed.

And this resulted in the following error:

```
Uncaught Exception:
Error: Object has been destroyed
    at BrowserWindow.<anonymous> (/xxx/node_modules/i18next-electron-fs-backend/lib/index.js:1:2472)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by linonetwo** [comment]
I think one possible solution is destroy `i18nextBackend` in `win.on('closed', event => {` also.

**Comment by linonetwo** [comment]
And actually 

```
  win.on('closed', event => {
    event.preventDefault();
  });
```

can't stop app from quitting when hitting `command + Q`

**Comment by reZach** [comment]
Linking [original issue](https://github.com/reZach/i18next-electron-fs-backend/issues/1)

**Comment by reZach** [comment]
@linonetwo There is code in main.js for the "activate" event that only creates window if the window is null. I believe this needs to be changed to create a window every time an "activate" event happens (because the BrowserWindow "close" event will set the window reference to null, which then breaks the i18next plugin because the i18next plugin has a reference to BrowserWindow that it has is now destroyed). This error is specific to mac os since the "activate" event only exists for mac os. All other os the app will be destroyed and this error would not occur.

I believe all you need to do is call `.mainBindings(ipcMain, win, fs)` again whenever the "activate" event happens. This code below should re-create the BrowserWindow and appropriately bind the i18next plugin. Try making these changes and tell me if it works (make this change in **main.js**). 
```javascript
app.on("activate", () => {
  // old
  /*if (win === null) {
    createWindow();
  }*/
  createWindow(); 
});
```

**Comment by linonetwo** [comment]
No, I still get `Object has been destroyed`:

<img width="672" alt="截屏2020-01-28下午1 55 46" src="https://user-images.githubusercontent.com/3746270/73239029-eb50c500-41d5-11ea-8d99-189068b8f2b5.png">

I think we can't prevent `win` object to be destroyed, we can only try no to use it if it is destroyed.

I'm doing so in IPC related code:

```js
ipcMain.on('start-server', async (event, args) => {
  // prevent "Object has been destroyed" error, after await, win may have destroyed due to close of window
  const reply = (...params) => event.sender.isDestroyed() ? null : event.reply(...params)

// ...
          reply('generate-keys-succeed');
// ...

```

Maybe you have to check `win.isDestroyed()` in `i18next-electron-fs-backend`? So this might still belongs to `i18next-electron-fs-backend` side.

**Comment by reZach** [comment]
@linonetwo I've commented the fix [here](https://github.com/reZach/i18next-electron-fs-backend/issues/1#issuecomment-579580635). The issue has been fixed in the i18next-electron-fs-backend package. You should get version `1.1.2` for the fix and add the code mentioned in [the comment](https://github.com/reZach/i18next-electron-fs-backend/issues/1#issuecomment-579580635).
